client/views/admin/adminGoal.ejs, client/views/community/partials/goal-completion.ejs, server/db/createTablesScript-base-example.sql, server/db/v2-db-upgrade.sql, server/model/goal.js, server/routes/admin/adminGoalRoutes.js, server/routes/community/topicRoutes.js, server/service/goalService.js, server/service/topicService.js
=> Completable

client/public/css/custom.css, client/views/admin/partials/createActivity.ejs, client/views/admin/partials/createAssessment.ejs, client/views/community/goal.ejs, client/views/community/partials/topic-activity.ejs, client/views/community/partials/topic-assessment.ejs, client/views/community/partials/topic-main.ejs, client/views/community/partials/topic-navigation.ejs, client/views/community/partials/topic-summary.ejs, client/views/community/topic.ejs, server/db/createTablesScript-base-example.sql, server/db/v2-db-upgrade.sql, server/model/assessment.js, server/model/completedAssessment.js, server/model/topic.js, server/routes/admin/adminTopicRoutes.js, server/routes/community/goalRoutes.js, server/routes/community/topicRoutes.js, server/service/assessmentService.js, server/service/goalService.js, server/service/resourceService.js, server/service/topicService.js, server/service/userService.js
=> Assessment threshold milestone #1

server/db/createTablesScript-base-example.sql, server/model/tag.js, server/model/tagged.js, server/routes/apiAuthRoutes.js, server/service/tagService.js
this is on pause. (#95 and #94 need to be taken care of first)
=> 34 resources should be able to be categorized using non hirarchical tags

server/controller/apis/goalController.js, server/controller/apis/tagController.js, server/controller/authController.js, server/routes/apiAuthRoutes.js, server/routes/apiUnauthRoutes.js, server/routes/apis/goalRoutes.js, server/service/goalService.js, server/service/tagService.js
In progress tag getAll working with authentication. Pausing to work on #94 to continue back here
=> 100 create a perfect api examle with tags

README.md
Un-needed information in the readme, was part of coding coach project.
=> Updated the readme to remove coding coach line

README.md
- Minor change to the Database setup section for clarity 
- Updated "Current features" to reflect change to current features over summer development 
- Updated "What's next" section to reflect the goals for the end of fall MVP launch.
=> Refined the readme to reflect current development

server/controller/apis/userController.js, server/controller/userController.js, server/service/goalService.js, server/service/topicService.js, server/service/userService.js
This bug came from fef860b490903bcde1656424911d7a9271c99e69. This works fine for windows machines but not for Linux based systems due to the different file system behaviors. 
Related issue: https://github.com/nodejs/node/issues/36968
=> fix imports for user model

server/controller/apis/resourceController.js, server/routes/apis/resourceRoutes.js, server/service/resourceService.js
Adds delete resources by id handler. Delete requests sent to /api/v1/auth/resources/:id will now remove resources given an id. Finishes resource api stack.
=> Adds delete resources by id handler

server/agoraApi.yaml
Accessed via http://localhost:4200/api-docs/
=> Swagger API Docs

client/agora/public/css/gallery/note-gallery.css, client/agora/public/js/dashboard.js, client/agora/views/dashboard/partials/gallery/note-gallery.ejs, client/agora/views/dashboard/partials/topic/edit-note.ejs
Changes: Added search by name to dashboard, gave onclick event to topics and goals on dashboard to get to note, fixed bug on dashboard where ellipsis was not visible, changed overflow handling on delete topic modal
=> Misc Bug Fixes and Search Function

client/agora/public/css/gallery/note-gallery.css, client/agora/public/js/dashboard.js, client/agora/views/dashboard/partials/gallery/grid-template.ejs, client/agora/views/dashboard/partials/gallery/list-template.ejs, client/agora/views/dashboard/partials/gallery/list-toggle.ejs, client/agora/views/dashboard/partials/gallery/note-gallery.ejs, client/agora/views/dashboard/partials/gallery/rename-modal.ejs
-Changed ids of elements to respect list view vs grid view
-updated more options menu functions to work on both types of views
-changed the code layout so that code rendering for each view is done in separate files
=> Added list view to dashboard

client/agora/public/css/gallery/note-gallery.css, client/agora/public/js/dashboard.js, client/agora/views/community/community-gallery.ejs, client/agora/views/dashboard/partials/gallery/grid-template.ejs, client/agora/views/dashboard/partials/gallery/list-template.ejs
-Preliminary action for implementing fetch
-added characters to ids to indicate whether they are goals or topics
-no new functionality
-just modifying existing elements to accommodate changes
=> Updating ids in dashboard

server/controller/apis/topicController.js
=> 192 eslint integration

client/agora/public/js/topic-view.js
- declared global variable tabName
- removed unused variables
=> Resolved Issue #213 and other minor updates

server/controller/apis/resourceController.js, server/controller/apis/topicController.js
Updated resourceController and topicController to validate the visibility field from the request body before assigning it. Used the existing code in goalController as a template.
=> Added validation for visibility update on save<Object> functions.

server/service/workspaceService.js
Commit was never pushed to recently merged branch.
=> Patches PR #253 - changes visibility of getAllVisibleWorkspaces

server/controller/apis/discussionController.js, server/db/createTablesScript-base-example.sql, server/service/discussionService.js
I created a database from the main sql file and all of my teams routes work. I have tested them all and they work. 
I want to make sure that is the same for the other routes as well so, if you guys can confirm @Mike-Volchko @KyleRess-Liere.
If you want to use my database connection you can...
I spun this one up purely to share
PG_USER = shared
PG_HOST = withered-sky-836100.cloud.neon.tech
PG_PASSWORD = CZid54aBAloy
PG_DATABASE = class
PG_PORT = 5432
PG_SSL = true
=> Fix for database changes caused by goal and workspace change

server/model/comment.js, server/service/discussionService.js
@MaxEnglish requested this feature for the front end
=> Add user_rating to comments

client/agora/public/js/topic-view.js
Resolved issue of multiple active tabs when rendering topics
=> Topic tab bugfix

.vscode/settings.json, server/controller/apis/sharedEntityController.js, server/db/createTablesScript-base-example.sql, server/model/sharedEntity.js, server/routes/apiAuthRoutes.js, server/routes/apis/sharedEntityRoutes.js, server/service/sharedEntityService.js
Added the structure for sharedEntities
=> Added sharedEntity router/controller/service

client/agora/public/js/topic-view.js
- automatically map resources to topics whenever resource created/edited
- implemented functionality on edit/save suneditor icons
=> topic-updating

client/agora/views/dashboard/partials/gallery/grid-template.ejs, server/controller/apis/workspaceController.js, server/controller/dashboardController.js, server/old-routes/admin/adminWorkspaceRoutes.js
added logic in dashboard controller to get topics for ownerWorkspace rather than always being blank
=> Fixed ownerWorkspace so it actually adds the associated topics

client/agora/views/dashboard/partials/gallery/grid-template.ejs
Topics are now required to be part of workspace so add creates a workspace
=> Changed add for dashboard

server/controller/apis/resourceController.js, server/controller/apis/topicController.js, server/controller/apis/workspaceController.js, server/service/resourceService.js, server/service/topicService.js, server/service/workspaceService.js
Visibility changed to represent correct values. Public = 2, share = 1, private = 0
=> Service Layer Visibility Changes

client/agora/public/css/gallery/note-gallery.css, client/agora/public/css/styles.css, client/agora/views/about.ejs, client/agora/views/dashboard/partials/gallery/dropdown.ejs, client/agora/views/dashboard/partials/gallery/grid-template.ejs, client/agora/views/index.ejs
- Updated tag to be better sized
- Updated delte icon to have color
- updated home page spacing
- added about seection about students contributions
=> Dashboard UI buffs

.env.example, server/db/createTablesScript-base-example.sql
Initial test site is up. Building out todo list.
=> 300 final presentaiton clean up and testing

client/agora/views/about.ejs, client/agora/views/dashboard/dashboard.ejs, client/agora/views/dashboard/partials/gallery/note-gallery.ejs, client/agora/views/index.ejs, client/agora/views/partials/topmenu.ejs, client/agora/views/partials/welcome.ejs
Immediate responsive issues fixed for the home page.
=> responsive issues fixed

client/agora/views/dashboard/partials/topic/topic-view.ejs
=> sharing link removed from topic / edit screen. only place it was found

client/agora/public/js/topic-view.js, server/agoraApi.yaml, server/controller/apis/tagController.js, server/controller/apis/workspaceController.js, server/db/createDatabase.sql, server/model/tagged.js, server/routes/apis/tagRoutes.js, server/service/tagService.js, server/service/workspaceService.js
Tagged API created and client side working!
Completes #306
=> 306 tags are not showing up when returning to a saved workspace

client/agora/public/js/topic-view.js
=> found issue with id's and resources preventing multiple editors

client/agora/public/js/topic-view.js, server/controller/apis/topicController.js, server/service/topicService.js
getting these in main, not complete yet.
=> 313 investiagte fix file uploads for workspaces topics resources

client/agora/public/css/agora-theme.css, client/agora/public/js/scripts.js, client/agora/views/user-signup.ejs, client/agora/views/website/privacy.ejs, client/agora/views/website/terms.ejs, server/routes/pagesRoutes.js
=> 42 add terms of service

client/agora/views/website/privacy.ejs
=> adjusted tos

client/agora/public/css/gallery/note-gallery.css, client/agora/public/js/dashboard.js, client/agora/public/js/topic-view.js, client/agora/views/dashboard/partials/gallery/grid-template.ejs, server/agoraApi.yaml, server/controller/apis/resourceController.js, server/controller/apis/tagController.js, server/controller/apis/topicController.js, server/controller/apis/workspaceController.js, server/controller/dashboardController.js, server/controller/profileController.js, server/db/createDatabase.sql, server/model/resource.js, server/model/topic.js, server/model/user.js, server/model/workspace.js, server/routes/apiAuthRoutes.js, server/routes/apis/tagRoutes.js, server/routes/apis/workspaceRoutes.js, server/routes/userRoutes.js, server/service/discussionService.js, server/service/resourceService.js, server/service/searchService.js, server/service/tagService.js, server/service/topicService.js, server/service/userService.js, server/service/workspaceService.js
This is a big one, it includes completion of #227 and branch #326 
It also includes tags on workspace items #355  and fix for the deletion of tags which broke when the id# numbers changed to uuid #372 
This change has breaking database changes!! you will need to drop your db and recreate.
=> 355 worspace items do not show tags just bio chem placeholders

client/agora/views/dashboard/partials/gallery/list-template.ejs
=> fix for list view tags

client/agora/public/js/topic-view.js, client/agora/views/partials/jsincludes.ejs
Katex has an NPM package, but since the editor is rendered entirely on the client-side, I obviously couldn't use it for this.
=> Implemented Katex

.env.example, client/agora/views/dashboard/side-menu/side-menu.ejs, client/agora/views/partials/topmenu.ejs, client/agora/views/profile/manage.ejs, client/agora/views/profile/user.ejs, client/agora/views/sign-in.ejs, client/agora/views/user-signup.ejs, package.json, server/agora.js, server/controller/authController.js, server/controller/userController.js, server/db/createDatabase.sql, server/routes/authRoutes.js, server/routes/userRoutes.js, server/service/userService.js
=> Google sso

client/agora/public/css/agora-theme.css, client/agora/public/js/dashboard.js, client/agora/public/js/scripts.js, client/agora/views/community/community.ejs, client/agora/views/dashboard/partials/gallery/grid-template.ejs, client/agora/views/dashboard/partials/gallery/list-template.ejs, client/agora/views/dashboard/side-menu/side-menu.ejs, client/agora/views/user-signup.ejs, server/controller/authController.js, server/routes/authRoutes.js, server/routes/dashboardRoutes.js
I pushed this back on August 1st and forgot to make a PR before I left for the summer. 
* I fixed some login stuff
* I improved the dashboard
* I added client-side settings (don't know if I like my implementation, but if it looks good, then we'll go with it)
=> Changes from the end of the summer

.vscode/settings.json
This is the updated way of doing the automatic linting. On my machine, the formatOnSave didn't even do anything. Might be deprecated.
=> Fix settings json file

client/agora/public/css/note.css, client/agora/public/css/topic.css, client/agora/public/js/dashboard.js, client/agora/public/js/topic-view.js, client/agora/views/dashboard/partials/topic/agnes-modal.ejs, client/agora/views/dashboard/partials/topic/comment-template.ejs, client/agora/views/dashboard/partials/topic/discussion-modal.ejs, client/agora/views/dashboard/partials/topic/topic-view.ejs, package.json
1. created the a bootstrap modal for the user-interface
2. Inside the modal, we included the paper, notes buttons
3. The citations buttons are also included in the modal
4. But it is missing the actual cards for the citations and we have a plan how we gonna implement that
=> added the first part of the ui and some functionalities

server/agoraApi.yaml
=> altered swagger ui server url to https

client/agora/public/css/topic.css, client/agora/public/js/agnesAI.js, client/agora/views/dashboard/partials/topic/agnes-modal.ejs, client/agora/views/partials/jsincludes.ejs
Resolves #459  
Citation types are now in a dropdown, they were previously just buttons side by side.
NOTE: Current behavior just logs the selected type, will be implementing the appropriate content formating with #458
=> Changing citation types to dropdown

client/agora/public/css/topic.css, client/agora/public/js/topic-view.js, client/agora/views/dashboard/partials/topic/topic-view.ejs, server/controller/apis/resourceController.js, server/controller/apis/topicController.js, server/controller/apis/workspaceController.js
The original goal of this is functional.. It did require a bit of re-work on the topic.js / client side js.. which has led to some new bugs.. I believe at this point though that they should be dealt with in their own tickets. So I am moving this into main for now, not planning on deploying yet but for basic use it is functional enough (dev work).
=> 463 fix redo replace the new topic resource pop up

client/agora/public/js/state/stateManager.js, server/service/resourceService.js, server/service/userService.js
Quick fix for postgresql upgade bug querying resources for topics.
=> Merge sharing and client

client/agora/public/css/topic.css, client/agora/public/js/dashboard.js, client/agora/public/js/editorMain.js, client/agora/public/js/editorManager.js, client/agora/public/js/state/stateManager.js, server/controller/apis/workspaceController.js
=> fixed the ordering of resources and added a default resource

client/agora/public/css/topic.css, client/agora/public/js/editorManager.js, server/controller/authController.js, server/controller/userController.js
=> 496 resource title visibility

client/agora/public/js/friends.js, client/agora/views/dashboard/side-menu/side-menu.ejs, client/agora/views/friends/partials/gallery/grid-template.ejs, server/controller/apis/friendController.js, server/model/friendship.js, server/model/user.js, server/service/friendService.js
=> modifications on the friend page

client/agora/public/js/controllers/clientTagController.js, client/agora/public/js/editorMain.js, client/agora/public/js/editorManager.js, client/agora/public/js/state/stateManager.js, client/agora/views/dashboard/partials/topic/topic-view.ejs, client/agora/views/profile/manage.ejs, server/controller/apis/tagController.js, server/controller/apis/userController.js, server/model/tagged.js, server/routes/apis/userRoutes.js, server/routes/topicRoutes.js, server/service/userService.js
=> 510 tags are broken

client/agora/public/js/dashboard.js, client/agora/public/js/state/stateManager.js, client/agora/views/dashboard/partials/gallery/grid-template.ejs, server/controller/apis/sharedEntityController.js, server/controller/userController.js, server/service/userService.js
=> 509 dashboard search is broken

server/controller/apis/friendController.js, server/service/userService.js
=> 519 friend requests should generate an email

.vscode/settings.json, client/agora/public/js/agnesAI.js, server/controller/apis/aiController.js
This is a good first step, much more to do..
=> 522 test implement gpt 4 for agnes

client/agora/public/js/controllers/clientResourceController.js, client/agora/public/js/editorManager.js, client/agora/public/js/state/stateManager.js, server/controller/apis/resourceController.js, server/db/createDatabase.sql, server/db/v2-db-upgrade.sql, server/model/resource.js, server/routes/topicRoutes.js, server/service/resourceService.js
DB update for prod:: 
-- #524-work-needs-a-version-or-method-to-ensure-new-work-is-overwritten
alter table resources add column current_version INTEGER DEFAULT 1;
alter table resources add column modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
=> 524 work needs a version or method to ensure that new work is not overwritten by old work

client/agora/public/js/dashboard.js, client/agora/public/js/editorMain.js, client/agora/views/dashboard/partials/gallery/grid-template.ejs
Issue: #533
Now, when the user clicks on a topic, it is displayed by default on the editor page.
To achieve this, I included the topic ID in the URL, as you can see below:
=> fix: clicking on a topic should display it

client/agora/public/css/agora-theme.css, client/agora/views/user-signup.ejs, server/controller/userController.js
Added honeypot Field in user Form
In Controllers we just check if there is anything in the field, if yes just return an error.
The honeypot field has a class name of address-field.
see issue #537
=> Added Honeypot Field

client/agora/public/js/user.js, client/agora/views/add-friends/partials/gallery/note-gallery.ejs, client/agora/views/profile/manage.ejs, server/controller/apis/userController.js, server/controller/userController.js, server/routes/userRoutes.js, server/service/userService.js
Issue: https://github.com/agorafoundation/agora/issues/394
Added Option for users to now update their username alongside first/last name and bio.
=> fix: users can now change their username
